### ISSUE TITLE
Commented escape characters end up in the json

### ISSUE THREAD

**Issue by tradiff** [muhammadmuzzammil1998/jsonc#10]
Commented escape characters are leaking into the output JSON, resulting in invalid JSON.
For example, if you pass this input JSONC into `ToJSON`:
```jsonc
{
  "test1": "string with \" escape char"
  //"test2": "string with \" escape char"
}
```

The output is:
```json
{"test1":"string with \" escape char"\"}
```

Note the erroneous `\"` towards the end, which makes this invalid JSON.

**Comment by muhammadmuzzammil1998** [comment]
Thanks!
