### ISSUE TITLE
Package gives a 404

### ISSUE THREAD

**Issue by arlyon** [muhammadmuzzammil1998/jsonc#18]
Hi!

Thanks for your  work on this library. It seems like muzzammil.xyz/jsonc is no longer available.

```
go: downloading muzzammil.xyz/jsonc v1.0.0
internal/fs/turbo_json.go:15:2: unrecognized import path "muzzammil.xyz/jsonc": reading https://muzzammil.xyz/jsonc?go-get=1: 404 Not Found
make: *** [Makefile:28: go-turbo] Error 1
```

Are you aware of this? Maybe we should update the docs to recommend using the github repo url instead?

Thanks

Alex

**Comment by muhammadmuzzammil1998** [comment]
Thank you for using the package and for bringing the issue to my attention. The issue you reported was related to a redirect problem, but it has now been resolved. 

If you continue to experience any issues, please don't hesitate to let me know. I appreciate your feedback.

**Comment by pwright** [comment]
I'm still getting this issue:

```
$ go install muzzammil.xyz/jsonc@latest
go: muzzammil.xyz/jsonc@latest: unrecognized import path "muzzammil.xyz/jsonc": parse https://muzzammil.xyz/jsonc?go-get=1: no go-import meta tags (meta tag github.com/muhammadmuzzammil1998/jsonc did not match import path muzzammil.xyz/jsonc)

```
