### ISSUE TITLE
Getting error when installing package. Go version: "go version go1.21.5 linux/amd64"

### ISSUE THREAD

**Issue by harpaldhillon** [muhammadmuzzammil1998/jsonc#20]
go install muzzammil.xyz/jsonc@latest                                             1 
go: muzzammil.xyz/jsonc@latest: unrecognized import path "muzzammil.xyz/jsonc": parse https://muzzammil.xyz/jsonc?go-get=1: no go-import meta tags (meta tag github.com/muhammadmuzzammil1998/jsonc did not match import path muzzammil.xyz/jsonc)

**Comment by muhammadmuzzammil1998** [comment]
Hi @harpaldhillon 

To install it as a command line, you can try jsonc-cli ([muhammadmuzzammil1998/jsonc-cli](https://github.com/muhammadmuzzammil1998/jsonc-cli)).

```bash
$ go install muzzammil.xyz/jsonc-cli@latest
go: downloading muzzammil.xyz/jsonc-cli v0.0.0-20201231201421-a6416cbcd010
go: finding module for package muzzammil.xyz/jsonc
go: finding module for package muzzammil.xyz/go-check
go: downloading muzzammil.xyz/go-check v0.0.0-20201230163914-d911bcc21d36
go: found muzzammil.xyz/go-check in muzzammil.xyz/go-check v0.0.0-20201230163914-d911bcc21d36
go: found muzzammil.xyz/jsonc in muzzammil.xyz/jsonc v1.0.0
$ jsonc-cli --version
 🎉 jsonc-cli
  🤖 Version: 1.0
  🌐 Source: https://muzzammil.xyz/jsonc-cli
$ jsonc-cli --help
Usage of jsonc-cli:
  -asis
        Prints the JSONC as-is
  -i string
        Source file
  -o string
        Destination file
  -p    Just prints the output instead of saving it
  -v    Checks if a jsonc file is valid or not (use with -i)
  -version
        Prints version
```

This package won't be installed. From the error you pasted, it could be a server-side issue which shows that go was not directed at the package. It is working as of now.

Thanks
