### ISSUE TITLE
Using jsonc as CLI command

### ISSUE THREAD

**Issue by arulrajnet** [muhammadmuzzammil1998/jsonc#9]
Do you have plan to release this as CLI command.? Basically we need to release this as bin file and takes input as arguments or sysin

**Comment by muhammadmuzzammil1998** [comment]
I hadn't given it much of a thought. Sounds nice, thanks. 
Any suggestions for the functionalities other than simple jsonc to json conversion?

**Comment by muhammadmuzzammil1998** [comment]
Done 👍 

https://github.com/muhammadmuzzammil1998/jsonc-cli
